### ISSUE TITLE
Desk buttons 'Show Values', 'Show Info' to globally set scribble mode do not work

### ISSUE THREAD

**Issue by phunkyg** [phunkyg/ReaControl24#3]
When these buttons are pressed, it should switch the 'default' mode of all of the scribble strips to a particular text value, such as name, values, info or group.
It does set the default so if a track is 'touched' by another value changing, then after a few seconds it will revert to the new default.

**Comment by Disruptormon** [comment]
Code now in place to handle the 4 x "show" buttons left of scribble.
Names shows channel names
Values shows level values
Group - untested...should show group
Info shows pan values

Changed timer from 3 seconds to 1 second for scribble context-sensitive values to switch back to selected "show" option

**Comment by phunkyg** [comment]
Fixed in v1.1.3
