### ISSUE TITLE
Pro control Compatability

### ISSUE THREAD

**Issue by lazlooose** [phunkyg/ReaControl24#6]
I would love to see greater support for the pro control module, notably: scribble strips and, counter and VU meters.  Some progress was made by @phasewalker @phunkyg and @Disruptormon already in terms of figuring out how the pro control announces on the phasewalker fork.

 I would be happy to assist with my extremely basic understanding of python if someone could point me to where to begin.

also since I have a pro control I can test it. 

thanks LZ

**Comment by phunkyg** [comment]
That's great Lazlooose. We will track progress on this and its components in the project area:
[link to card](https://github.com/phunkyg/ReaControl24/projects/1#card-14966453)

**Comment by phunkyg** [comment]
Moved to project
